# Generated by Django 5.1.2 on 2024-11-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_historicalpurchase_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
