# Generated by Django 5.1.4 on 2024-12-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcategory',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('client', 'Client'), ('seller', 'Seller'), ('admin', 'Admin')], max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='store.product')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalBrand',
        ),
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
    ]
