# Generated by Django 5.1.4 on 2024-12-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_historicalcategory_history_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbasketproduct',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='historicalbasketproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbasketproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicerecord',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicerecord',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicerecord',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='historicalproductpricechange',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproductpricechange',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='historicalreview',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalreview',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, limit_choices_to={'role_id': 12}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HistoricalBasket',
        ),
        migrations.DeleteModel(
            name='HistoricalBasketProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalInvoiceRecord',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalProductPriceChange',
        ),
        migrations.DeleteModel(
            name='HistoricalPurchase',
        ),
        migrations.DeleteModel(
            name='HistoricalReview',
        ),
    ]
